#include "Nexiora/Research/NxAutonomousExecution.h"

#include "Nexiora/NCP/Research/NxExperimentRunner.h"
#include "Nexiora/NCP/Research/NxJournal.h"
#include "Nexiora/NCP/Research/NxPromotion.h"
#include "Nexiora/NCP/Research/NxResearchEvidence.h"
#include "Nexiora/Research/NxDiscoveryEngine.h"
#include "Nexiora/Research/NxResearchGraph.h"
#include "Nexiora/Research/NxResearchGraphExporter.h"
#include "Nexiora/Research/NxResearchScheduler.h"

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <time.h>

#ifdef _WIN32
#include <direct.h>
#define NX_MKDIR(path) _mkdir(path)
#else
#include <sys/stat.h>
#include <sys/types.h>
#define NX_MKDIR(path) mkdir(path, 0777)
#endif

static void nx_ae_copy(char* dst, size_t dst_size, const char* src)
{
    size_t i;
    if (!dst || dst_size == 0) return;
    if (!src) src = "";
    for (i = 0; i + 1 < dst_size && src[i] != '\0'; ++i)
    {
        dst[i] = src[i];
    }
    dst[i] = '\0';
}

static void nx_ae_join(char* dst, size_t dst_size, const char* a, const char* b)
{
    const char* sep = "";
    size_t la, lb, ls, total;
    char tmp[1024];
    if (dst == NULL || dst_size == 0U || a == NULL || b == NULL) return;
    la = strlen(a); lb = strlen(b);
    if (la > 0U && a[la - 1U] != '/' && a[la - 1U] != '\\') sep = "\\";
    ls = strlen(sep);
    if (la > SIZE_MAX - ls || la + ls > SIZE_MAX - lb) return;
    total = la + ls + lb;
    if (total + 1U > (size_t)dst_size || total + 1U > sizeof(tmp)) return;
    if (la > 0U) memcpy(tmp, a, la);
    if (ls > 0U) memcpy(tmp + la, sep, ls);
    if (lb > 0U) memcpy(tmp + la + ls, b, lb);
    tmp[total] = '\0';
    memmove(dst, tmp, total + 1U);
    return;
}

static void nx_ae_mkdir_ignore(const char* path)
{
    if (path && path[0] != '\0')
    {
        (void)NX_MKDIR(path);
    }
}

static int nx_ae_write_text(const char* path, const char* text)
{
    FILE* file;
    if (!path || !text) return 0;
    file = fopen(path, "wb");
    if (!file) return 0;
    fputs(text, file);
    fclose(file);
    return 1;
}

static int nx_ae_write_metrics(
    const char* path,
    const NxAutonomousExecutionResult* result)
{
    FILE* file;
    if (!path || !result) return 0;
    file = fopen(path, "wb");
    if (!file) return 0;
    fprintf(file, "{\n");
    fprintf(file, "  \"experimentsDiscovered\": %zu,\n", result->experiments_discovered);
    fprintf(file, "  \"experimentsExecuted\": %zu,\n", result->experiments_executed);
    fprintf(file, "  \"evidenceGenerated\": %zu,\n", result->evidence_generated);
    fprintf(file, "  \"promotionCandidates\": %zu,\n", result->promotion_candidates);
    fprintf(file, "  \"graphNodes\": %zu,\n", result->graph_nodes);
    fprintf(file, "  \"graphEdges\": %zu\n", result->graph_edges);
    fprintf(file, "}\n");
    fclose(file);
    return 1;
}

static int nx_ae_write_summary(
    const char* path,
    const NxAutonomousExecutionResult* result)
{
    FILE* file;
    if (!path || !result) return 0;
    file = fopen(path, "wb");
    if (!file) return 0;
    fprintf(file, "Nexiora First Autonomous Research Execution\n");
    fprintf(file, "==========================================\n\n");
    fprintf(file, "Experiments discovered : %zu\n", result->experiments_discovered);
    fprintf(file, "Experiments executed   : %zu\n", result->experiments_executed);
    fprintf(file, "Evidence generated     : %zu\n", result->evidence_generated);
    fprintf(file, "Promotion candidates   : %zu\n", result->promotion_candidates);
    fprintf(file, "Knowledge graph nodes  : %zu\n", result->graph_nodes);
    fprintf(file, "Knowledge graph edges  : %zu\n\n", result->graph_edges);
    fprintf(file, "Human approval gate    : ACTIVE\n");
    fprintf(file, "Runtime promotion      : NOT AUTOMATIC\n");
    fclose(file);
    return 1;
}

static int nx_ae_write_report(
    const char* path,
    const NxAutonomousExecutionResult* result)
{
    FILE* file;
    if (!path || !result) return 0;
    file = fopen(path, "wb");
    if (!file) return 0;
    fprintf(file, "# Nexiora First Autonomous Research Execution\n\n");
    fprintf(file, "This report was generated by `nexiora research run`.\n\n");
    fprintf(file, "## Results\n\n");
    fprintf(file, "- Experiments discovered: %zu\n", result->experiments_discovered);
    fprintf(file, "- Experiments executed: %zu\n", result->experiments_executed);
    fprintf(file, "- Evidence generated: %zu\n", result->evidence_generated);
    fprintf(file, "- Promotion candidates: %zu\n", result->promotion_candidates);
    fprintf(file, "- Graph nodes: %zu\n", result->graph_nodes);
    fprintf(file, "- Graph edges: %zu\n\n", result->graph_edges);
    fprintf(file, "## Safety\n\n");
    fprintf(file, "Nexiora may recommend. Only a human may promote.\n");
    fclose(file);
    return 1;
}

const char* NxAutonomousExecution_StatusToString(
    NxAutonomousExecutionStatus status)
{
    switch (status)
    {
        case NX_AUTONOMOUS_EXECUTION_OK: return "OK";
        case NX_AUTONOMOUS_EXECUTION_INVALID_ARGUMENT: return "InvalidArgument";
        case NX_AUTONOMOUS_EXECUTION_IO_ERROR: return "IoError";
        case NX_AUTONOMOUS_EXECUTION_DISCOVERY_FAILED: return "DiscoveryFailed";
        case NX_AUTONOMOUS_EXECUTION_SCHEDULER_FAILED: return "SchedulerFailed";
        case NX_AUTONOMOUS_EXECUTION_RUNNER_FAILED: return "RunnerFailed";
        case NX_AUTONOMOUS_EXECUTION_EVIDENCE_FAILED: return "EvidenceFailed";
        case NX_AUTONOMOUS_EXECUTION_PROMOTION_FAILED: return "PromotionFailed";
        case NX_AUTONOMOUS_EXECUTION_GRAPH_FAILED: return "GraphFailed";
        default: return "Unknown";
    }
}

NxAutonomousExecutionStatus NxAutonomousExecution_RunDefault(
    const char* workspace_root,
    NxAutonomousExecutionResult* result_out)
{
    char research_path[NX_AUTONOMOUS_EXECUTION_PATH_MAX];
    char sessions_path[NX_AUTONOMOUS_EXECUTION_PATH_MAX];
    char session_path[NX_AUTONOMOUS_EXECUTION_PATH_MAX];
    char journal_path[NX_AUTONOMOUS_EXECUTION_PATH_MAX];
    char path[NX_AUTONOMOUS_EXECUTION_PATH_MAX];
    NxExperimentDescriptor storage[8];
    const NxExperimentDescriptor* ready[8];
    NxDiscoveryEngine discovery;
    NxResearchScheduler scheduler;
    NxJournal journal;
    NxExperimentRunner runner;
    NxResearchGraph graph;
    size_t ready_count;
    size_t i;
    uint32_t manifest_node = 0;

    if (!workspace_root || workspace_root[0] == '\0' || !result_out)
    {
        return NX_AUTONOMOUS_EXECUTION_INVALID_ARGUMENT;
    }

    memset(result_out, 0, sizeof(*result_out));

    nx_ae_join(research_path, sizeof(research_path), workspace_root, "Research");
    nx_ae_join(sessions_path, sizeof(sessions_path), research_path, "Sessions");
    nx_ae_join(session_path, sizeof(session_path), sessions_path, "first_autonomous_execution");
    nx_ae_copy(result_out->session_path, sizeof(result_out->session_path), session_path);

    nx_ae_mkdir_ignore(research_path);
    nx_ae_mkdir_ignore(sessions_path);
    nx_ae_mkdir_ignore(session_path);

    if (NxDiscoveryEngine_Init(&discovery, storage, 8) != NX_DISCOVERY_STATUS_OK)
    {
        return NX_AUTONOMOUS_EXECUTION_DISCOVERY_FAILED;
    }

    {
        NxExperimentDescriptor descriptor;
        descriptor.id = "EXP-VECTOR-001";
        descriptor.name = "Vector growth policy baseline";
        descriptor.component = "NCP.Vector";
        descriptor.owner = "Nexiora Research Lab";
        descriptor.kind = NX_EXPERIMENT_KIND_BENCHMARK;
        descriptor.state = NX_EXPERIMENT_STATE_READY;
        descriptor.priority = 90;
        (void)NxDiscoveryEngine_Register(&discovery, &descriptor);

        descriptor.id = "EXP-EVIDENCE-001";
        descriptor.name = "Evidence lifecycle smoke test";
        descriptor.component = "NRL.Evidence";
        descriptor.owner = "Nexiora Research Lab";
        descriptor.kind = NX_EXPERIMENT_KIND_RESEARCH;
        descriptor.state = NX_EXPERIMENT_STATE_READY;
        descriptor.priority = 80;
        (void)NxDiscoveryEngine_Register(&discovery, &descriptor);

        descriptor.id = "EXP-GRAPH-001";
        descriptor.name = "Research graph export smoke test";
        descriptor.component = "NRL.Graph";
        descriptor.owner = "Nexiora Research Lab";
        descriptor.kind = NX_EXPERIMENT_KIND_RESEARCH;
        descriptor.state = NX_EXPERIMENT_STATE_READY;
        descriptor.priority = 70;
        (void)NxDiscoveryEngine_Register(&discovery, &descriptor);
    }

    ready_count = NxDiscoveryEngine_Discover(
        &discovery,
        NxDiscoveryPredicate_Ready,
        NULL,
        ready,
        8);
    result_out->experiments_discovered = ready_count;

    if (NxResearchScheduler_Init(&scheduler, 8) != NX_RESEARCH_SCHEDULER_STATUS_OK)
    {
        return NX_AUTONOMOUS_EXECUTION_SCHEDULER_FAILED;
    }

    for (i = 0; i < ready_count; ++i)
    {
        NxResearchTaskDescriptor task;
        task.id = (unsigned int)(i + 1);
        task.name = ready[i]->id;
        task.priority = (int)ready[i]->priority;
        task.max_runs = 1;
        task.completed_runs = 0;
        task.next_tick = 0;
        task.state = NX_RESEARCH_TASK_STATE_PENDING;
        if (NxResearchScheduler_Add(&scheduler, &task) != NX_RESEARCH_SCHEDULER_STATUS_OK)
        {
            NxResearchScheduler_Destroy(&scheduler);
            return NX_AUTONOMOUS_EXECUTION_SCHEDULER_FAILED;
        }
    }

    nx_ae_join(journal_path, sizeof(journal_path), session_path, "journal.jsonl");
    if (nx_journal_open(&journal, journal_path) != NX_OK)
    {
        NxResearchScheduler_Destroy(&scheduler);
        return NX_AUTONOMOUS_EXECUTION_IO_ERROR;
    }

    if (nx_experiment_runner_initialize(&runner, session_path, &journal) != NX_OK)
    {
        nx_journal_close(&journal);
        NxResearchScheduler_Destroy(&scheduler);
        return NX_AUTONOMOUS_EXECUTION_RUNNER_FAILED;
    }

    if (NxResearchGraph_Init(&graph) != NX_RESEARCH_GRAPH_OK)
    {
        nx_experiment_runner_shutdown(&runner);
        nx_journal_close(&journal);
        NxResearchScheduler_Destroy(&scheduler);
        return NX_AUTONOMOUS_EXECUTION_GRAPH_FAILED;
    }

    (void)NxResearchGraph_AddNode(
        &graph,
        NX_RESEARCH_NODE_MANIFEST,
        "First Autonomous Execution Manifest",
        &manifest_node);

    for (i = 0; i < ready_count; ++i)
    {
        NxResearchTaskDescriptor task;
        NxExperimentRunResult run;
        NxResearchEvidence evidence;
        NxPromotionReview review;
        uint32_t experiment_node = 0;
        uint32_t evidence_node = 0;
        uint32_t promotion_node = 0;
        uint32_t edge_id = 0;

        if (NxResearchScheduler_SelectNext(&scheduler, &task) != NX_RESEARCH_SCHEDULER_STATUS_OK)
        {
            break;
        }

        if (nx_experiment_runner_execute(&runner, task.name, &run) != NX_OK)
        {
            NxResearchGraph_Shutdown(&graph);
            nx_experiment_runner_shutdown(&runner);
            nx_journal_close(&journal);
            NxResearchScheduler_Destroy(&scheduler);
            return NX_AUTONOMOUS_EXECUTION_RUNNER_FAILED;
        }
        result_out->experiments_executed++;

        if (nx_research_evidence_from_run(&run, 1.0, &evidence) != NX_OK)
        {
            NxResearchGraph_Shutdown(&graph);
            nx_experiment_runner_shutdown(&runner);
            nx_journal_close(&journal);
            NxResearchScheduler_Destroy(&scheduler);
            return NX_AUTONOMOUS_EXECUTION_EVIDENCE_FAILED;
        }
        result_out->evidence_generated++;

        if (nx_promotion_review_from_evidence(&evidence, &review) != NX_OK)
        {
            NxResearchGraph_Shutdown(&graph);
            nx_experiment_runner_shutdown(&runner);
            nx_journal_close(&journal);
            NxResearchScheduler_Destroy(&scheduler);
            return NX_AUTONOMOUS_EXECUTION_PROMOTION_FAILED;
        }

        if (review.decision == NX_PROMOTION_DECISION_CANDIDATE)
        {
            result_out->promotion_candidates++;
        }

        (void)NxResearchGraph_AddNode(&graph, NX_RESEARCH_NODE_EXPERIMENT, task.name, &experiment_node);
        (void)NxResearchGraph_AddNode(&graph, NX_RESEARCH_NODE_EVIDENCE, evidence.experiment_id, &evidence_node);
        (void)NxResearchGraph_AddNode(&graph, NX_RESEARCH_NODE_PROMOTION_RECOMMENDATION, review.experiment_id, &promotion_node);
        (void)NxResearchGraph_AddEdge(&graph, manifest_node, experiment_node, NX_RESEARCH_EDGE_DECLARES, "declares", &edge_id);
        (void)NxResearchGraph_AddEdge(&graph, experiment_node, evidence_node, NX_RESEARCH_EDGE_PRODUCES, "produces", &edge_id);
        (void)NxResearchGraph_AddEdge(&graph, evidence_node, promotion_node, NX_RESEARCH_EDGE_SUPPORTS, "supports", &edge_id);

        (void)NxResearchScheduler_MarkCompleted(&scheduler, task.id, 0);
    }

    result_out->graph_nodes = NxResearchGraph_GetNodeCount(&graph);
    result_out->graph_edges = NxResearchGraph_GetEdgeCount(&graph);

    nx_ae_join(path, sizeof(path), session_path, "graph.json");
    (void)NxResearchGraph_ExportJson(&graph, path);
    nx_ae_join(path, sizeof(path), session_path, "graph.dot");
    (void)NxResearchGraph_ExportDot(&graph, path);
    nx_ae_join(path, sizeof(path), session_path, "graph.svg");
    (void)NxResearchGraph_ExportSvg(&graph, path);

    nx_ae_join(path, sizeof(path), session_path, "knowledge.json");
    (void)nx_ae_write_text(path, "{\n  \"status\": \"first autonomous execution knowledge snapshot\",\n  \"humanApprovalGate\": true\n}\n");

    nx_ae_join(path, sizeof(path), session_path, "manifest.snapshot.json");
    (void)nx_ae_write_text(path, "{\n  \"session\": \"first_autonomous_execution\",\n  \"runtimePromotion\": \"human-only\"\n}\n");

    nx_ae_join(path, sizeof(path), session_path, "metrics.json");
    if (!nx_ae_write_metrics(path, result_out))
    {
        NxResearchGraph_Shutdown(&graph);
        nx_experiment_runner_shutdown(&runner);
        nx_journal_close(&journal);
        NxResearchScheduler_Destroy(&scheduler);
        return NX_AUTONOMOUS_EXECUTION_IO_ERROR;
    }

    nx_ae_join(path, sizeof(path), session_path, "summary.txt");
    (void)nx_ae_write_summary(path, result_out);
    nx_ae_join(path, sizeof(path), session_path, "report.md");
    (void)nx_ae_write_report(path, result_out);

    nx_ae_copy(
        result_out->message,
        sizeof(result_out->message),
        "First autonomous research execution completed; waiting for human approval");

    NxResearchGraph_Shutdown(&graph);
    nx_experiment_runner_shutdown(&runner);
    nx_journal_close(&journal);
    NxResearchScheduler_Destroy(&scheduler);

    return NX_AUTONOMOUS_EXECUTION_OK;
}
