#include "Nexiora/Multimodal/NxMultimodalIngestion.h"

#include <ctype.h>
#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if defined(_WIN32)
#include <direct.h>
#define nx_mm_mkdir(path) _mkdir(path)
#else
#include <sys/stat.h>
#include <sys/types.h>
#define nx_mm_mkdir(path) mkdir((path), 0777)
#endif

static void nx_mm_copy(char* dst, size_t size, const char* src) {
    if (dst == NULL || size == 0U) return;
    if (src == NULL) { dst[0] = '\0'; return; }
    (void)snprintf(dst, size, "%s", src);
    dst[size - 1U] = '\0';
}
static int nx_mm_exists(const char* path) { FILE* f=fopen(path,"rb"); if(f==NULL)return 0; fclose(f); return 1; }
static const char* nx_mm_ext(const char* path) { const char* dot=strrchr(path,'.'); const char* slash=strrchr(path,'/'); const char* back=strrchr(path,'\\'); const char* sep=slash>back?slash:back; return (dot!=NULL && (sep==NULL || dot>sep))?dot:""; }
static int nx_mm_eq_ci(const char* a,const char* b){ while(*a!='\0'&&*b!='\0'){ if(tolower((unsigned char)*a)!=tolower((unsigned char)*b))return 0; ++a;++b;} return *a=='\0'&&*b=='\0'; }
static uint16_t nx_mm_u16le(const unsigned char* p){ return (uint16_t)((uint16_t)p[0]|((uint16_t)p[1]<<8U)); }
static uint32_t nx_mm_u32le(const unsigned char* p){ return (uint32_t)p[0]|((uint32_t)p[1]<<8U)|((uint32_t)p[2]<<16U)|((uint32_t)p[3]<<24U); }
static void nx_mm_sidecar(const char* source,char* out,size_t size){ const char* dot=nx_mm_ext(source); size_t n=(size_t)(dot-source); if(dot[0]=='\0') n=strlen(source); if(n+5U>size){ if(size>0U)out[0]='\0'; return;} memcpy(out,source,n); memcpy(out+n,".txt",5U); }
static NxMediaType nx_mm_type(const char* path,const unsigned char* magic,size_t n){ const char* e=nx_mm_ext(path); if(n>=5U&&memcmp(magic,"%PDF-",5U)==0)return NX_MEDIA_PDF; if(n>=12U&&memcmp(magic,"RIFF",4U)==0&&memcmp(magic+8,"WAVE",4U)==0)return NX_MEDIA_WAV; if(nx_mm_eq_ci(e,".txt")||nx_mm_eq_ci(e,".csv")||nx_mm_eq_ci(e,".json")||nx_mm_eq_ci(e,".xml"))return NX_MEDIA_TEXT; if(nx_mm_eq_ci(e,".md"))return NX_MEDIA_MARKDOWN; if(nx_mm_eq_ci(e,".pdf"))return NX_MEDIA_PDF; if(nx_mm_eq_ci(e,".wav"))return NX_MEDIA_WAV; if(nx_mm_eq_ci(e,".mp3")||nx_mm_eq_ci(e,".flac")||nx_mm_eq_ci(e,".ogg")||nx_mm_eq_ci(e,".m4a"))return NX_MEDIA_AUDIO; if(nx_mm_eq_ci(e,".mp4")||nx_mm_eq_ci(e,".mkv")||nx_mm_eq_ci(e,".avi")||nx_mm_eq_ci(e,".mov")||nx_mm_eq_ci(e,".webm"))return NX_MEDIA_VIDEO; if(nx_mm_eq_ci(e,".png")||nx_mm_eq_ci(e,".jpg")||nx_mm_eq_ci(e,".jpeg")||nx_mm_eq_ci(e,".bmp")||nx_mm_eq_ci(e,".webp")||nx_mm_eq_ci(e,".tif")||nx_mm_eq_ci(e,".tiff"))return NX_MEDIA_IMAGE; return NX_MEDIA_UNKNOWN; }
const char* NxMultimodal_StatusToString(NxMultimodalStatus s){ switch(s){case NX_MM_OK:return "OK";case NX_MM_PARTIAL:return "PARTIAL";case NX_MM_INVALID_ARGUMENT:return "INVALID_ARGUMENT";case NX_MM_NOT_FOUND:return "NOT_FOUND";case NX_MM_UNSUPPORTED:return "UNSUPPORTED";case NX_MM_IO_ERROR:return "IO_ERROR";case NX_MM_OUTPUT_TOO_SMALL:return "OUTPUT_TOO_SMALL";case NX_MM_TRANSCRIPT_REQUIRED:return "TRANSCRIPT_REQUIRED";case NX_MM_FORMAT_ERROR:return "FORMAT_ERROR";default:return "UNKNOWN";} }
const char* NxMultimodal_MediaTypeToString(NxMediaType t){ switch(t){case NX_MEDIA_TEXT:return "text";case NX_MEDIA_MARKDOWN:return "markdown";case NX_MEDIA_PDF:return "pdf";case NX_MEDIA_WAV:return "wav";case NX_MEDIA_AUDIO:return "audio";case NX_MEDIA_VIDEO:return "video";case NX_MEDIA_IMAGE:return "image";default:return "unknown";} }
NxMultimodalStatus NxMultimodal_Probe(const char* source,NxMediaProbe* out){ FILE* f; unsigned char head[64]={0}; size_t n; long end; if(source==NULL||source[0]=='\0'||out==NULL)return NX_MM_INVALID_ARGUMENT; memset(out,0,sizeof(*out)); f=fopen(source,"rb"); if(f==NULL)return NX_MM_NOT_FOUND; n=fread(head,1U,sizeof(head),f); if(fseek(f,0L,SEEK_END)!=0){fclose(f);return NX_MM_IO_ERROR;} end=ftell(f); fclose(f); if(end<0L)return NX_MM_IO_ERROR; out->file_size=(unsigned long long)end; out->type=nx_mm_type(source,head,n); nx_mm_copy(out->source_path,sizeof(out->source_path),source); nx_mm_sidecar(source,out->transcript_path,sizeof(out->transcript_path)); out->transcript_available=nx_mm_exists(out->transcript_path); if(out->type==NX_MEDIA_WAV){ if(n<44U)return NX_MM_FORMAT_ERROR; out->channels=nx_mm_u16le(head+22U); out->sample_rate=nx_mm_u32le(head+24U); {uint32_t rate=nx_mm_u32le(head+28U); uint32_t data=nx_mm_u32le(head+40U); if(rate>0U)out->duration_ms=(unsigned int)(((uint64_t)data*1000U)/rate);} } return out->type==NX_MEDIA_UNKNOWN?NX_MM_UNSUPPORTED:NX_MM_OK; }
static int nx_mm_make_dirs(const char* root,char* dir,size_t size){ int rc; (void)snprintf(dir,size,"%s/Knowledge",root); rc=nx_mm_mkdir(dir); if(rc!=0&&errno!=EEXIST)return 0; (void)snprintf(dir,size,"%s/Knowledge/Multimodal",root); rc=nx_mm_mkdir(dir); return rc==0||errno==EEXIST; }
static int nx_mm_join_knowledge_path(char* out,size_t size,const char* dir,const char* safe){ size_t a=strlen(dir),b=strlen(safe); const char suffix[]=".nxknowledge"; size_t c=sizeof(suffix)-1U; if(a+1U+b+c+1U>size)return 0; memcpy(out,dir,a); out[a]='/'; memcpy(out+a+1U,safe,b); memcpy(out+a+1U+b,suffix,c+1U); return 1; }
static void nx_mm_safe_name(const char* title,char* out,size_t size){ size_t i,j=0U; for(i=0U;title[i]!='\0'&&j+1U<size;++i){ unsigned char ch=(unsigned char)title[i]; if(isalnum(ch))out[j++]=(char)tolower(ch); else if(j>0U&&out[j-1U]!='_')out[j++]='_'; } while(j>0U&&out[j-1U]=='_')--j; if(j==0U){nx_mm_copy(out,size,"media");return;} out[j]='\0'; }
static NxMultimodalStatus nx_mm_copy_text(FILE* in,FILE* out,size_t* count){ unsigned char buf[4096]; size_t n,total=0U; while((n=fread(buf,1U,sizeof(buf),in))>0U){ size_t i; for(i=0U;i<n;++i){ unsigned char ch=buf[i]; if(ch=='\r')continue; if(ch=='\t'||ch=='\n'||(ch>=32U&&ch<127U)||ch>=128U){ if(fputc((int)ch,out)==EOF)return NX_MM_IO_ERROR; ++total; } } } if(ferror(in))return NX_MM_IO_ERROR; *count=total; return NX_MM_OK; }
static NxMultimodalStatus nx_mm_pdf_text(FILE* in,FILE* out,size_t* count){ int ch; int inside=0,escape=0; size_t total=0U; while((ch=fgetc(in))!=EOF){ if(!inside){if(ch=='(')inside=1;continue;} if(escape){ int mapped=ch; if(ch=='n')mapped='\n'; else if(ch=='r')mapped='\r'; else if(ch=='t')mapped='\t'; if(fputc(mapped,out)==EOF)return NX_MM_IO_ERROR; ++total; escape=0; continue;} if(ch=='\\'){escape=1;continue;} if(ch==')'){inside=0;if(fputc('\n',out)==EOF)return NX_MM_IO_ERROR;++total;continue;} if(ch=='\n'||ch=='\r'||ch=='\t'||(ch>=32&&ch<127)){if(fputc(ch,out)==EOF)return NX_MM_IO_ERROR;++total;} } *count=total; return total>0U?NX_MM_PARTIAL:NX_MM_FORMAT_ERROR; }
NxMultimodalStatus NxMultimodal_Ingest(const char* root,const char* source,const char* title,NxIngestionResult* result){ NxMediaProbe p; NxMultimodalStatus s; FILE* in=NULL; FILE* out=NULL; char dir[NX_MM_MAX_PATH],safe[NX_MM_MAX_TITLE],path[NX_MM_MAX_PATH]; const char* content=source; size_t count=0U; if(root==NULL||source==NULL||title==NULL||result==NULL||root[0]=='\0'||title[0]=='\0')return NX_MM_INVALID_ARGUMENT; memset(result,0,sizeof(*result)); s=NxMultimodal_Probe(source,&p); result->status=s; result->type=p.type; if(s!=NX_MM_OK)return s; if((p.type==NX_MEDIA_AUDIO||p.type==NX_MEDIA_VIDEO||p.type==NX_MEDIA_IMAGE||p.type==NX_MEDIA_WAV)&&p.transcript_available==0){result->status=NX_MM_TRANSCRIPT_REQUIRED; nx_mm_copy(result->message,sizeof(result->message),"Se requiere archivo sidecar .txt junto al medio.");return result->status;} if(p.type==NX_MEDIA_AUDIO||p.type==NX_MEDIA_VIDEO||p.type==NX_MEDIA_IMAGE||p.type==NX_MEDIA_WAV)content=p.transcript_path; if(!nx_mm_make_dirs(root,dir,sizeof(dir))){result->status=NX_MM_IO_ERROR;return result->status;} nx_mm_safe_name(title,safe,sizeof(safe)); if(!nx_mm_join_knowledge_path(path,sizeof(path),dir,safe)){result->status=NX_MM_OUTPUT_TOO_SMALL;return result->status;} in=fopen(content,"rb"); if(in==NULL){result->status=NX_MM_NOT_FOUND;return result->status;} out=fopen(path,"wb"); if(out==NULL){fclose(in);result->status=NX_MM_IO_ERROR;return result->status;} (void)fprintf(out,"format=nxknowledge/1\ntitle=%s\nmedia_type=%s\nsource=%s\nsource_bytes=%llu\n",title,NxMultimodal_MediaTypeToString(p.type),source,p.file_size); if(p.type==NX_MEDIA_WAV)(void)fprintf(out,"sample_rate=%u\nchannels=%u\nduration_ms=%u\n",p.sample_rate,p.channels,p.duration_ms); (void)fputs("content_begin\n",out); if(p.type==NX_MEDIA_PDF)s=nx_mm_pdf_text(in,out,&count); else s=nx_mm_copy_text(in,out,&count); (void)fputs("\ncontent_end\n",out); if(fclose(in)!=0||fclose(out)!=0){result->status=NX_MM_IO_ERROR;return result->status;} if(s!=NX_MM_OK&&s!=NX_MM_PARTIAL){(void)remove(path);result->status=s;return s;} result->status=s; result->extracted_bytes=count; nx_mm_copy(result->knowledge_path,sizeof(result->knowledge_path),path); nx_mm_copy(result->message,sizeof(result->message),s==NX_MM_PARTIAL?"Contenido extraido parcialmente; conservar evidencia original.":"Contenido normalizado y persistido."); return s; }
